
- rule: Terminal shell in container
  desc: A shell was used as the entrypoint/exec point of a container with an attached terminal.
  condition: >
    spawned_process and container
    and shell_procs and proc.tty != 0
    and container_entrypoint
  output: >
    A shell was spawned in a container with an attached terminal (user=%user.name user_loginuid=%user.loginuid
    %container.info shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline terminal=%proc.tty container_id=%container.id image=%container.image.repository)
  priority: WARNING
  tags: [container, shell, mitre_execution]

- rule: Write below etc
  desc: an attempt to write to any file below /etc
  condition: write_etc_common
  output: "File below /etc opened for writing (user=%user.name user_loginuid=%user.loginuid command=%proc.cmdline parent=%proc.pname pcmdline=%proc.pcmdline file=%fd.name program=%proc.name gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)"
  priority: WARNING
  tags: [filesystem, mitre_persistence]

- rule: Unexpected outbound connection
  desc: Detect outbound network connections by unauthorized programs
  condition: >
    outbound
    and container
    and not (proc.name in (node, python3, mysqld))
  output: "Unexpected Outbound Connection (user=%user.name command=%proc.cmdline connection=%fd.name container_id=%container.id image=%container.image.repository)"
  priority: NOTICE
  tags: [network, mitre_command_and_control]

- rule: Launch Privileged Container
  desc: Detect the initial process started in a privileged container.
  condition: >
    container_started and container
    and container.privileged=true
  output: Privileged container started (user=%user.name user_loginuid=%user.loginuid command=%proc.cmdline %container.info image=%container.image.repository)
  priority: INFO
  tags: [container, cis, mitre_privilege_escalation, mitre_lateral_movement]
